### PR TITLE
sklearn cross_validation->model_selection

### PR DESCRIPTION
**Pull request by JorySchossau**
Updates use of sklearn to modern sklearn (allows to run in Google Colab python2 environment)

### CODE REVIEW

**Comment by JorySchossau** [comment]
Oh, #13 already includes this :)

**Comment by kstaats** [comment]
Jory,

My apology for the delayed response. Just now getting back to Karoo GP 
after a long break. I appreciate your bringing this to my attention, and 
in the new Python 3.x version I have incorporated the replacement 
module. Stay tuned, as I should have this fully tested and uploaded to 
github by the close of this weekend.

Thank you!

Cheers,
kai

> Updates use of sklearn to modern sklearn (allows to run in Google Colab python2 environment)
> You can view, comment on, or merge this pull request online at:
> 
>    https://github.com/kstaats/karoo_gp/pull/14
> 
> -- Commit Summary --
> 
>    * cross_validation->model_selection
> 
> -- File Changes --
> 
>      M modules/karoo_gp_base_class.py (2)
> 
> -- Patch Links --
> 
> https://github.com/kstaats/karoo_gp/pull/14.patch
> https://github.com/kstaats/karoo_gp/pull/14.diff
>

**Comment by JorySchossau** [comment]
Cant' way to use it! In empathy: software maintenance does take a lot of effort.

**Comment by kstaats** [comment]
This is now resolved with the new Karoo GP 2.3 for Python 3.6. Please sync with the latest build and enjoy the many improvements to the code. Thank you for your patience!

**Comment by kstaats** [comment]
Jory,

> Cant' way to use it! In empathy: software maintenance does take a lot of effort.

I hope this communication finds you well.

Karoo GP is now Python 3.8 functional with a work-around for Tensorflow 2.4.

https://github.com/kstaats/karoo_gp

We will have pip install soon!

Cheers,
kai

**Pull request closed without merging**
